### ISSUE TITLE
Multimodal Hydra Configs for Multiple Modalities

### ISSUE THREAD

**Issue by Oufattole** [Oufattole/meds-torch#144]
# Proposed Architecture Changes for Multimodal Model

## Naming Convention Updates
- [ ] `input_encoder` → `tokenization`
- [ ] `components/backbone` → `embedder`

### Dataset Updates
-  Implement modality tracking in PyTorch dataset
- Create mapping between codes and modality names
- Example structure:
```yaml
modalities:
    EHR: None  # Captures all codes
    ECG: [1, 5, 6]  # Specific ECG codes
    NOTE: [4]
```

### MultimodalModel Updates
We need to enable a hydra overridable mapping between:
  - Modality names → Input encoder
  - Modality names → Embedding model

We want to create default multimodal yamls for the MultimodalModel:
1. `model/multimodal_embedder`
2. `model/multimodal_input_encoder`

These both should provide a dictionary-based structure mapping the modality name to the respective embedder or input_encoder. The vision is to support the following experiment configuration structure:

```yaml
# @package *global*
defaults:
  - override /data: multimodal_pytorch_dataset
  - override /logger: wandb
  - override /model: multimodal_supervised
  - override /trainer: gpu

tags:
  - "mimiciv"
  - "triplet"
  - "transformer_encoder"

seed: 0

trainer:
  min_epochs: 1
  max_epochs: 10
  gradient_clip_val: 1.0

data:
  dataloader:
    batch_size: 64
    num_workers: 6
  max_seq_len: 128
  subsequence_sampling_strategy: "to_end"
  modalities:
    EHR: None  # Captures all codes
    ECG: [1, 5, 6]  # Specific ECG codes

model:
  optimizer:
    lr: 0.001
  modalities:
    EHR:
      tokenizer:
        type: triplet_encoder  # Defaults
        token_dim: 128
      encoder:
        type: triplet_transformer_encoder  # Defaults
        n_layers: 2
        nheads: 4
        dropout: 0
    ECG:
      tokenizer:
        type: ecg_tokenizer  # Defaults
        class: meds_torch.tokenizer.ecg_tokenizer.Model
        token_dim: ...  # Overrides

logger:
  wandb:
    tags: ${tags}
    group: "mimiciv_tokenization"
```
